project:
  type: website

website:
  title: "John Wilson"
  site-url: "https:johnwilson.co"

  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - work.qmd
      - about.qmd
    logo: "/images/fav.png"
    background: "#0454a4"
    pinned: true
    collapse: true
  page-footer:
    center: 
      - text: "Website by John Armistead Wilson. Copyright 2024."
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



