project:
  type: website

website:
  title: "John Wilson"
  site-url: "https:johnwilson.co"
  favicon: "/images/fav.png"
  navbar:
    title: "John Wilson" # this is the website title as it appears in the top left corner -- clicking on this will jump you back to your landing page from where ever you are
    logo: "/images/fav.png"
    logo-alt: "John Wilson"
    pinned: true
    collapse: true

    #title: false # change this to false!
    #logo: "/images/fav.png"
    #logo-alt: "Alt text for logo"

    right: # align navbar items to the right/left/center
      - work.qmd
      - about.qmd
      - icon: newspaper
        href: https://johnwilson.beehiiv.com
      - icon: envelope
        href: mailto:johnawilson@gmail.com

    # logo: "/images/fav.png"
    # background: "#0454a4"
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, John Armistead Wilson"
    right:
      - icon: github
        href: https://github.com/armistead
format:
  html:
    theme:
      - styles.scss
    mainfont: Roboto
    toc: true
    page-layout: full

execute:
  freeze: auto


