project:
  type: website

website:
  title: "John Wilson"
  site-url: "https:johnwilson.co"

  navbar:
    title: "John Wilson" # this is the website title as it appears in the top left corner -- clicking on this will jump you back to your landing page from where ever you are
    
    #title: false # change this to false!
    #logo: "/images/fav.png"
    #logo-alt: "Alt text for logo"


    right: # align navbar items to the right/left/center
      - work.qmd
      - projects.qmd
      - icon: newspaper
        href: https://johnwilson.beehiiv.com
      - icon: envelope
        href: mailto:johnawilson@gmail.com

    logo: "/images/fav.png"
    background: "#E8EDE7"
    pinned: true
    collapse: true
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, John Armistead Wilson"
    right:
      - icon: github
        href: https://github.com/armistead
format:
  html:
    theme: 
      - styles.scss
    toc: true
#    css: styles.scss
#    toc: true

execute:
  freeze: auto


